Replaced autoconf with meson build files
Resolves: #699

Signed-off-by: Nikos Mavrogiannopoulos <n.mavrogiannopoulos@gmail.com>

diff --git a/tests/haproxy-proxyproto b/tests/haproxy-proxyproto
--- a/tests/haproxy-proxyproto
+++ b/tests/haproxy-proxyproto
@@ -90,7 +90,12 @@ rm -f ${HACONFIG}
 sed -e 's|@HAPORT@|'${HAPORT}'|g' -e 's|@PORT@|'${PORT}'|g' -e 's|@ADDRESS@|'${ADDRESS}'|g' ${srcdir}/data/haproxy-proxyproto.cfg >${HACONFIG}
 ${CMDNS2} ${HAPROXY} -f ${HACONFIG} -d & HAPID=$!
 
-sleep 3
+sleep 1
+if ! kill -0 ${HAPID} 2>/dev/null; then
+	echo "haproxy failed to start (config incompatible with this version?)"
+	exit 1
+fi
+sleep 2
 
 # Run clients
 echo " * Getting cookie from ${ADDRESS}:${HAPORT}..."
